apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db
type: Opaque
data:
  MYSQL_PASSWORD: QW5rdQ==
  MYSQL_USER: YW5rdXNo
  MYSQL_DATABASE: dG9kbw==
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==