apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: db
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 5G
  storageClassName: standard
  accessModes:
    - ReadWriteOnce

